@startuml

class InventoryManager {

    +createInventory():
    +loadInventory();
}

class Inventory {
    -ObservableList<InventoryItem> inventoryItems;

    +save();

}

class InventoryItem {
    -String serialNumber;
    -String name;
    -BigDecimal value;



}

@enduml