@startuml

class InventoryManager {

    +createInventory():
    +loadInventory();
}

class Inventory {
    -String path;
    -ObservableList<InventoryItem> inventoryItems;

    +save();
    +saveAsHtml(String path);
    +saveAsTsv(String path);
    +saveAsJson(String path);
    +addItem(InventoryItem item);
    +deleteItem(InventoryItem item);
    +deleteAllItems();
}

class InventoryItem {
    -String serialNumber;
    -String name;
    -BigDecimal value;

    +getSerialNumber();
    +setSerialNumber(String serialNumber);
    +getName();
    +setName(String name);
    +getValue();
    +setValue(BigDecimal value);
}

@enduml