@startuml

class InventoryManager {
    +loadInventory();
    +exportToJSON(List<InventoryItem> items, File destinationFile);
    +exportToHTML(List<InventoryItem> items, File destinationFile);
    +exportToTSV(List<InventoryItem> items, File destinationFile);
}

class InventoryItem {
    -String serialNumber;
    -String name;
    -BigDecimal value;

    +getSerialNumber();
    +setSerialNumber(String serialNumber);
    +getName();
    +setName(String name);
    +getValue();
    +setValue(float value);
}

@enduml